### ISSUE TITLE
Make "Insecure connection" warning optional

### ISSUE THREAD

**Issue by arubaxi** [thelounge/thelounge#4117]
### Feature Description

When we connect to a non-encrypted port (6667), thelounge shows a warning adding `.not-secure`, `.not-secure-tooltip` and `.not-secure-icon` classes to the network name.

In case thelounge is used on the same host as the ircd server, there is no need real of using SSL/TLS ircd port, unless you're paranoid about someone with unauthorized access to your server could intercept your data between the app and ircd running on the localhost, which could be done as well as using SSL/TLS in case the attacker has root access.

Please consider adding a config option that makes possible suppressing this warning.

**Comment by fnutt** [comment]
This won't be fixed, as it has been asked about multiple times before and been denied.

You can hide the warnings easly with css.

```
.not-secure-tooltip,
.not-secure-icon {
    display: none;
}

#sidebar .not-secure .channel-list-item[data-type="lobby"] {
    color: <your choice of colour>;
}

.not-secure .channel-list-item[data-type="lobby"].active,
.not-secure .channel-list-item[data-type="lobby"] .lobby-wrap:hover {
    color: <your choice of colour>;
}
```

**Comment by Jay2k1** [comment]
> In case thelounge is used on the same host as the ircd server, there is no need real of using SSL/TLS ircd port

If you connect thelounge to 127.0.0.1, it does not show the warnings for this very reason.

**Comment by lps-rocks** [comment]
I found a way around this. If you're running `thelounge` and `znc` in two separate docker containers, use a bind mount to make the the SSL certificate that `znc` is using available in the `thelounge` docker container. Then add the environment variable `NODE_EXTRA_CA_CERTS ` to point to the path of the bind mounted `znc` certificate. 

Make sure you've updated your ZNC config to use separate configuration parameters for the SSL certificate as indicated here: https://wiki.znc.in/Signed_SSL_certificate#ZNC_1.7.0+

Example docker-compose config:
```
znc:
    container_name: znc
    image: linuxserver/znc:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/storage/containers/znc/data:/config
    ports:
      - 7778:7778/tcp

  thelounge:
    container_name: thelounge
    image: linuxserver/thelounge
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=America/New_York
     - NODE_EXTRA_CA_CERTS=/config/ca.crt
    volumes:
     - /mnt/storage/containers/thelounge/config:/config
     - /mnt/storage/containers/znc/data/cert.pem:/config/ca.crt:ro
    ports:
     - 9000:9000
    restart: "unless-stopped"
```
