### ISSUE TITLE
Away messages are not collapsed

### ISSUE THREAD

**Issue by FodT** [thelounge/thelounge#4583]
The option to hide/collapse status messages does not apply to PM sessions. This can lead to very polluted windows full of ‘is away’, ‘is back’ messages.

**Comment by mooomooo** [comment]
+1.  As a workaround in the meantime, I use a custom style (e.g. with the [Stylus](https://add0n.com/stylus.html) browser plugin) to manually hide them:

```
div[data-type=back], div[data-type=away] {
    display: none !important;
}
```

**Comment by Dav1dde** [comment]
> +1. As a workaround in the meantime, I use a custom style (e.g. with the [Stylus](https://add0n.com/stylus.html) browser plugin) to manually hide them

You don't need a browser plugin for custom CSS, [you can inject CSS directly from your settings](https://thelounge.chat/docs/guides/custom-css).

**Comment by SimplyLinn** [comment]
To improve on that custom style provided, to get the "collapse" feel, I've opted for this CSS styling:
```css
div[data-type=back], div[data-type=away] {
    display: none !important;
}

div[data-type=back]:has(+ :not(div[data-type=away])) {
    display: flex !important;
}

:not(div[data-type=back]) + div[data-type=away] {
    display: flex !important;
}
```
It keeps the first "away" and the last "is back" message in a string, but hides the rest.

It's not perfect, and if you type something while someone is away, breaking the chain so the next message will be an "is back", then the chain may collapse into nothingness, but it's something
