### ISSUE TITLE
User color not applied to /me-actions

### ISSUE THREAD

**Issue by SimplyLinn** [thelounge/thelounge#4741]
### Just want to get the color back in your client?
Go to the bottom of this issue, I put a workaround there.

---

- _Node version:_ 20.2.0
- _Browser version:_ Google Chrome 113.0.5672.127 (Official Build) (64-bit) (+ chrome on android)
- _Device, operating system:_
  - _Server:_ VPS, Debian GNU/Linux 11 (bullseye)
  - _Client:_ Windows 10/11 (Desktop), MacOS Catalina 10.15 (Desktop), Android 12 (Phone)
- _The Lounge version:_ 4.4.0 (I checked the changelog between this version and master, and it doesn't seem to have been anything relating to this issue committed, so I did not find it necessary to test on latest master)

---

![image](https://github.com/thelounge/thelounge/assets/1394292/76a960e2-b6c5-4e0a-8748-b1b03071bea9)

As shown in the above screenshot, I've shown how it used to look in 4.3.X with the message I indicated.

As far as I can tell, this change came about with the Vue3 update, and while there's specific styling to ensure that this behavior happens, I'm unsure if this was an intentional change of the UI, or just an oversight when doing everything else relating to Vue3. I tried to skim the commit messages/changelogs to see if anything mentioned this behavior, but could not find anything.

[Snippet from [style.css](https://github.com/thelounge/thelounge/blob/ae9d312b2a06a43a6e18424d5c583a61244940ba/client/css/style.css#L1557-L1561)]
```css
#chat .msg[data-type="action"] .from,
#chat .msg[data-type="action"] .content,
#chat .msg[data-type="action"] .user {
	color: #f39c12;
}
```

I would at least like confirmation whether this new behavior is the intended behavior or not.

If it is the intended behavior, I will, change this bug report to a feature request and start a dialogue about whether we should have nickname colorization of /me-actions, because that makes them far more easy to read to me.

If this is not the intended behavior then I may create a PR if I have the time to set up a thelounge dev environment without too much hassle to make sure any changes I make actually work and are sane.

## WORKAROUND

First, make sure you have the latest version of The Lounge installed, and if you do and it's still not fixed, continue following these instructions.

Since there are 2 themes present in thelounge, you need to pick the snipped meant for your theme. Default theme is the light mode, Morning theme is the dark/cyan mode.

Find the appropriate snippet and put it into `Settings -> Appearance -> Custom Stylesheet`

Remember to check whether this behavior has been reverted/reimplemented after you've updated The Lounge, and if so, remove the snippet from your Custom Stylesheets.

### Default theme
```css
#chat .msg[data-type="action"] .content .user { color: #50a656; }
#chat .msg[data-type="action"] .content .user.color-1 { color: #107ead; }
#chat .msg[data-type="action"] .content .user.color-2 { color: #a86500; }
#chat .msg[data-type="action"] .content .user.color-3 { color: #008a3c; }
#chat .msg[data-type="action"] .content .user.color-4 { color: #e00096; }
#chat .msg[data-type="action"] .content .user.color-5 { color: #f0000c; }
#chat .msg[data-type="action"] .content .user.color-6 { color: #000094; }
#chat .msg[data-type="action"] .content .user.color-7 { color: #006441; }
#chat .msg[data-type="action"] .content .user.color-8 { color: #00566e; }
#chat .msg[data-type="action"] .content .user.color-9 { color: #e6006b; }
#chat .msg[data-type="action"] .content .user.color-10 { color: #0d8766; }
#chat .msg[data-type="action"] .content .user.color-11 { color: #006b3b; }
#chat .msg[data-type="action"] .content .user.color-12 { color: #00857e; }
#chat .msg[data-type="action"] .content .user.color-13 { color: #00465b; }
#chat .msg[data-type="action"] .content .user.color-14 { color: #eb005a; }
#chat .msg[data-type="action"] .content .user.color-15 { color: #e62600; }
#chat .msg[data-type="action"] .content .user.color-16 { color: #0f8546; }
#chat .msg[data-type="action"] .content .user.color-17 { color: #e60067; }
#chat .msg[data-type="action"] .content .user.color-18 { color: #eb002b; }
#chat .msg[data-type="action"] .content .user.color-19 { color: #eb003f; }
#chat .msg[data-type="action"] .content .user.color-20 { color: #007a56; }
#chat .msg[data-type="action"] .content .user.color-21 { color: #095092; }
#chat .msg[data-type="action"] .content .user.color-22 { color: #000bde; }
#chat .msg[data-type="action"] .content .user.color-23 { color: #008577; }
#chat .msg[data-type="action"] .content .user.color-24 { color: #00367d; }
#chat .msg[data-type="action"] .content .user.color-25 { color: #007e9e; }
#chat .msg[data-type="action"] .content .user.color-26 { color: #006119; }
#chat .msg[data-type="action"] .content .user.color-27 { color: #007ea8; }
#chat .msg[data-type="action"] .content .user.color-28 { color: #3c8500; }
#chat .msg[data-type="action"] .content .user.color-29 { color: #e6007e; }
#chat .msg[data-type="action"] .content .user.color-30 { color: #c75300; }
#chat .msg[data-type="action"] .content .user.color-31 { color: #eb0400; }
#chat .msg[data-type="action"] .content .user.color-32 { color: #e60082; }
```

### Morning theme:
```css
#chat .msg[data-type="action"] .content .user { color: #b0bacf; }
#chat .msg[data-type="action"] .content .user.color-1 { color: #f7adf7; }
#chat .msg[data-type="action"] .content .user.color-2 { color: #abf99f; }
#chat .msg[data-type="action"] .content .user.color-3 { color: #86efdc; }
#chat .msg[data-type="action"] .content .user.color-4 { color: #c890eb; }
#chat .msg[data-type="action"] .content .user.color-5 { color: #f9a4b3; }
#chat .msg[data-type="action"] .content .user.color-6 { color: #f7999a; }
#chat .msg[data-type="action"] .content .user.color-7 { color: #f497b9; }
#chat .msg[data-type="action"] .content .user.color-8 { color: #f9a9d7; }
#chat .msg[data-type="action"] .content .user.color-9 { color: #85a7e3; }
#chat .msg[data-type="action"] .content .user.color-10 { color: #a8b8ff; }
#chat .msg[data-type="action"] .content .user.color-11 { color: #b695fc; }
#chat .msg[data-type="action"] .content .user.color-12 { color: #f4aead; }
#chat .msg[data-type="action"] .content .user.color-13 { color: #fc7cb1; }
#chat .msg[data-type="action"] .content .user.color-14 { color: #ff72e0; }
#chat .msg[data-type="action"] .content .user.color-15 { color: #8cb6ea; }
#chat .msg[data-type="action"] .content .user.color-16 { color: #f9857c; }
#chat .msg[data-type="action"] .content .user.color-17 { color: #ed9b82; }
#chat .msg[data-type="action"] .content .user.color-18 { color: #8df484; }
#chat .msg[data-type="action"] .content .user.color-19 { color: #ffcce3; }
#chat .msg[data-type="action"] .content .user.color-20 { color: #efcc81; }
#chat .msg[data-type="action"] .content .user.color-21 { color: #92a2ed; }
#chat .msg[data-type="action"] .content .user.color-22 { color: #f4d484; }
#chat .msg[data-type="action"] .content .user.color-23 { color: #97ea70; }
#chat .msg[data-type="action"] .content .user.color-24 { color: #fcbbba; }
#chat .msg[data-type="action"] .content .user.color-25 { color: #eef975; }
#chat .msg[data-type="action"] .content .user.color-26 { color: #c7ff93; }
#chat .msg[data-type="action"] .content .user.color-27 { color: #ffade1; }
#chat .msg[data-type="action"] .content .user.color-28 { color: #98ecf2; }
#chat .msg[data-type="action"] .content .user.color-29 { color: #91a2f5; }
#chat .msg[data-type="action"] .content .user.color-30 { color: #b19aea; }
#chat .msg[data-type="action"] .content .user.color-31 { color: #f2a4eb; }
#chat .msg[data-type="action"] .content .user.color-32 { color: #85f27d; }
```
