### ISSUE TITLE
Image preview broken in v4.4.3

### ISSUE THREAD

**Issue by leorg99** [thelounge/thelounge#4871]
I get the following error with image preview:
```
thelounge-1  | 2024-05-04 18:10:51 [ERROR] Failed to fetch changelog: TypeError: Expected value which is `predicate returns truthy for any value`, received values of types `boolean`.
```

Rolled back to v4.4.1 and it is working. 
Can't stay on v4.4.1 because sqlite db was updated in v4.4.3 and not sure if there is a way to roll it back.

**Comment by leorg99** [comment]
I think my [config](https://github.com/thelounge/thelounge/files/15210827/config.zip) is pretty basic. 

This is what it looks like:
![image](https://github.com/thelounge/thelounge/assets/16126495/2f7e4766-0bde-44b8-af7c-d371af670ff6)

Maybe it has something to do with the reverse proxy (Traefik): 
```
services:
  irc:
    image: ghcr.io/thelounge/thelounge:latest
    restart: always
    networks:
      - proxy
    ports:
      - "9001:9001" # identd
    volumes:
      - ./config:/var/opt/thelounge
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.thelounge.rule=Host(`REDACTED`)"
      - "traefik.http.routers.thelounge.service=thelounge"
      - "traefik.http.routers.thelounge.entryPoints=irc"

      # This tells traefik which port to send the packets to for the backend service.
      - "traefik.http.services.thelounge.loadbalancer.server.port=80"

      # Traefik will secure the connection between browser and then decrypt the packets and send it to the backend service.
      - "traefik.http.routers.thelounge.tls=true"

networks:
  proxy:
    external: true
    ```
