### ISSUE TITLE
IPv4 perrfered over IPv6 for outgoing connectings

### ISSUE THREAD

**Issue by iamtherobin** [thelounge/thelounge#4889]
I am running thelounge in docker compose with an IPv6 network setup the same way I do all my containers. I can access thelounge via IPv6 on the host machine and I can a receive successful IPv6 pings on thelounge's container via docker exec -it thelounge ping ipv6.google.com command.

Here is the docker compose file I use:
```
services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - 8580:9000
    restart: unless-stopped
    volumes:
      - ./thelounge-data:/var/opt/thelounge
    networks:
      - thelounge
    #network_mode: host

networks:
  thelounge:
    name: thelounge
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd12:3456:7890:22::/64
          gateway: fd12:3456:7890:22::1
        - subnet: 10.123.22.0/24
          gateway: 10.123.22.1
  ```
I even tested with host network mode but thelounge always makes its outgoing server connections via IPv4. If I modify config.js and change bind to "::" it will fail to connect to servers even though IPv6 connectivity to the container is working (container itself can still ping IPv6 addresses).
