### ISSUE TITLE
curl http://127.0.0.1:9000 - Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by SocksHelp** [thelounge/thelounge#4945]
I have thelounge running in docker with `reverseProxy: true` and `host: "127.0.0.1"`.
How can I find why `curl http://127.0.0.1:9000` outputs `curl: (56) Recv failure: Connection reset by peer`?

curl responds with the html if `host: undefined` is set, but not `host: "127.0.0.1"`.

`wget http://127.0.0.1:9000/` outputs
```
--2024-12-24 23:22:29--  http://127.0.0.1:9000/
Connecting to 127.0.0.1:9000... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
```

My docker-compose.yml file.
```
version: '2'
services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - /root/docker/thelounge:/var/opt/thelounge # bind lounge config from the host's file system
```

I asked in IRC. I can't find the support forum.
