### ISSUE TITLE
Disable timestamps altogether 

### ISSUE THREAD

**Issue by blixten85** [thelounge/thelounge#4950]
I want to request the ”feature” to disable the timestamp altogether in the client. Not just swap between 12 and 24hr time format.

**Comment by dgw** [comment]
Custom CSS

```css
div.msg span.time {
  display: none;
}
```
